import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "@/app/components/Navbar";
import "./globals.css";

const latoFont = Lato({
  weight: ["400", "700", "900"],
  style: ["normal"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "GameOtivity",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={latoFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
